--SELECT
SELECT * FROM FANCY_USER;
SELECT * FROM PRODUCT;
SELECT * FROM CART;
SELECT * FROM COUPON;
SELECT * FROM REVIEW;
SELECT * FROM CALCULATE;
SELECT * FROM ADMIN;

------------------------------------------------------------------------------
--테이블 삭제
DROP TABLE ADMIN;
DROP TABLE CALCULATE;
DROP TABLE REVIEW;
DROP TABLE COUPON;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE FANCY_USER;

------------------------------------------------------------------------------
--시퀸스 삭제
DROP SEQUENCE CALCULATE_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE COUPON_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE REVIEW_SEQ;
