--상의
----------------------------------------------------------------------------------------------
--T-SHIRT
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'랄프 반팔티','POLO','T-SHIRT',159000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'헤리티지 반팔티','SPAO','T-SHIRT',17910);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'크루 넥 반팔티','MUTANDARD','T-SHIRT',23790);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'수피마 코튼 반팔티','COOR','T-SHIRT',41800);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'드라이 핏 반팔티','NIKE','T-SHIRT',49000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'스몰아치 반팔티','YALE','T-SHIRT',29900);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'플라워로고 반팔티','WOOYOUNGMI','T-SHIRT',350000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'라인로고 반팔티','IAB STUDIO','T-SHIRT',78000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'데일리그래픽 반팔티','PATAGONIA','T-SHIRT',89000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'크랙아크 반팔티','SUPREME','T-SHIRT',154000);

--후드티
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'드라이핏 후드티','NIKE','HOODIE',85000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'아이앱로고 후드티','IAB STUDIO','HOODIE',85000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'코튼 백로고 후드티','WOOYOUNGMI','HOODIE',520000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'풀 지퍼 후드티','POLO','HOODIE',239000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'피그먼트 후드티','SOVERMENT','HOODIE',68400);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'톤 아치 후드티','YALE','HOODIE',48000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'하프 집업 후드티','ANOTHER OFFICE','HOODIE',85000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'릴렉스 후드티','STUSSY','HOODIE',229000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'퀄티드 후드티','JARA','HOODIE',79000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'헤비 패널 후드티','COS','HOODIE',175000);


--아우터
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'블루종 자켓','COS','OUTER',150000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'박시핏 자켓','JARA','OUTER',189000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'모던 린넨 자켓','POLO','OUTER',160000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'윈드러너 자켓','NIKE','OUTER',126000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'발마칸 자켓','COOR','OUTER',143000);

--남방 OR 셔츠
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'블랜드 체크 셔츠','JARA','SHIRT',59900);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'슬리브 린넨 셔츠','COS','SHIRT',98000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'클래식 핏 셔츠','POLO','SHIRT',121000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'시티보이 셔츠','MUTANDARD','SHIRT',48000);
INSERT INTO PRODUCT VALUES('TO'||PRODUCT_SEQ.NEXTVAL,'옥스퍼드 셔츠','DRAWFIT','SHIRT',52000);

COMMIT;

--신발
-----------------------------------------------------------------------------
--운동화
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'에어포스 1 로우','NIKE','sneakers',115000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'조던 1 로우','NIKE','sneakers',112000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'사카이 베이퍼와플 ','NIKE','sneakers',135000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'에어맥스 97','NIKE','sneakers',109000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'뉴발란스 992','NEW BALANCE','sneakers',128000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'뉴발란스 574','NEW BALANCE','sneakers',98000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'뉴발란스 530','NEW BALANCE','sneakers',117000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'삼바 OG 블랙','ADIDAS','sneakers',129000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'슈퍼스타 화이트','ADIDAS','sneakers',109000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'이지부스트 350 V2','ADIDAS','sneakers',170000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'젤 카야노 크림 블랙','ASICS','sneakers',118000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'오니츠카 타이거 멕시코','ASICS','sneakers',154000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'살로몬 XT-6','SALOMON','sneakers',179000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'컨버스 척테일러 로우','CONVERSE','sneakers',122000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'컨버스 척70 하이','CONVERSE','sneakers',101000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'올드스쿨 블랙','VANS','sneakers',58000);
INSERT INTO PRODUCT VALUES('SH'||PRODUCT_SEQ.NEXTVAL,'체커보드 슬립온','VANS','sneakers',51000);

COMMIT;

--악세사리
------------------------------------------------------------------------------
--모자
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'리버서블 버킷 햇','NIKE','cap',39900);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'트윌 캠프 캡','SUPREME','cap',42800);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'이미스 로고 캡','EMIS','cap',39900);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'베이직 트러커 캡','STUSSY','cap',41500);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'갭 플러그 패널 캡','PALACE','cap',57000);

--가방
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'메쉬 스트링 백팩','NEIKIDNIS','bag',65000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'트레이닝 더블 팩','NIKE','bag',28000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'트레일 블레이저 백팩','SALOMON','bag',105000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'크로스바디 새들 백','COS','bag',82000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'다니엘라 에코 백','A.P.C','bag',75000);

--시계
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'태그호이어 포뮬러 1','TAGHEUER','watch',198000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'PR516 크래노그래프','TISSOT','watch',170000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'쿼츠 레이디','JILLSTUART','watch',92000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'MTG-B300','G-SHOCK','watch',118000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'애플워치 9','APPLE','watch',209000);

--안경
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'에고 C1','GENTLE MONSTER','glasses',33000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'크로 02','GENTLE MONSTER','glasses',71000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'가우스 NC3','GENTLE MONSTER','glasses',83000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'에반 01','GENTLE MONSTER','glasses',143000);
INSERT INTO PRODUCT VALUES('AC'||PRODUCT_SEQ.NEXTVAL,'조디악 D02','GENTLE MONSTER','glasses',53000);
COMMIT;

--하의
-------------------------------------------------------------------------------
--반바지
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'스트레치 치노 반바지','POLO','shorts',159000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'블루 원턱 데님 반바지','WOOYOUNGMI','shorts',130000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'엘라스틱 코튼 반바지','COS','shorts',85000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'원턱 스웻 반바지','ZERO','shorts',32000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'레귤러 핏 반바지','MUTANDARD','shorts',29800);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'나이키 클럽 반바지','NIKE','shorts',59000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'립스탑 그린 반바지','IAB STUDIO','shorts',74000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'스트럭처 버뮤다 반바지','JARA','shorts',55900);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'투턱 카고 반바지','JARA','shorts',63900);

--데님
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'연청 스트레치 청바지','JARA','jeans',59900);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'스트레이트 청바지','POLO','jeans',129000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'블랙 세미와이드 청바지','DRAWFIT','jeans',75000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'테이퍼드 핏 청바지','MUTANDARD','jeans',42000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'인디고 오리지널 청바지','LEVIS','jeans',118300);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'화이트 포인트 청바지','A.P.C','jeans',184000);

--트레이닝 팬츠
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'테크 플리스 트레이닝 바지','NIKE','sweatpants',120000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'조던 조거 트레이닝 바지','NIKE','sweatpants',98000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'카펜더 트레이닝 바지','IAB STUDIO','sweatpants',163000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'스탠다드 트레이닝 바지','MUTANDARD','sweatpants',44000);
INSERT INTO PRODUCT VALUES('BO'||PRODUCT_SEQ.NEXTVAL,'카고 와이드 트레이닝 바지','COS','sweatpants',72000);

COMMIT;

